### ISSUE TITLE
KeOps compiling slow

### ISSUE THREAD

**Issue by patel-zeel** [awav/CGLB#4]
Hello,

I am executing the experiments on a single NVIDIA A100 SXM4 40 GB available on GCP and experiencing slow compiling of KeOps. It takes roughly 2 to 15 minutes of compiling before training of each set of experiments is started. 

Is this normal behaviour or something could be wrong with any of the dependencies?

Versions installed:

| library | version |
| :-- | :--: |
| tensorflow | 2.7.0 |
| tensorflow_probability | 0.15.0 |
| torch | 1.10.0+cu113 |
| gpytorch | 1.3.1 |
| gpflow | 2.3.0 |
| pykeops | 1.5 |
| Driver Version | 495.29.05 |
| CUDA Version | 11.5 |

**Comment by awav** [comment]
It depends solely on the dataset size and other factors such as your hardware configuration (GPU is not really a major factor here). If the dataset is reasonably small, I would recommend using TF version. It is better to ask KeOps maintainers "why compilation time takes long" :)

I'm closing this issue, but please re-open it if you have more questions.

**Comment by patel-zeel** [comment]
Thank you @awav
